/**
 * Document State Utilities
 * 
 * Centralized serialization and hashing utilities for document state.
 * Used by:
 * - useAutoSave.ts (autosave change detection)
 * - useHistory.ts (undo/redo deduplication)
 * - Future dirty-state tracking
 * 
 * This ensures consistent state comparison across all systems.
 */

import type { Layer, CanvasSettings, EffectsConfig } from '../types/gradient';

/**
 * Serializable document state shape
 * Includes only user-editable fields that meaningfully change the document
 */
export interface SerializableDocumentState {
  layers: Array<{
    id: string;
    name: string;
    visible: boolean;
    opacity: number;
    blendMode: string;
    locked: boolean;
    gradient: any;
    texture: any;
    animation: any;
    mask: any;
  }>;
  canvasSettings: {
    width: number;
    height: number;
    background?: string;
    backgroundColor?: string;
  };
  effects?: any;
  activeLayerId?: string;
}

/**
 * Fast hash function using djb2 algorithm
 * Provides fast and good distribution for state comparison
 */
function hashString(str: string): number {
  let hash = 5381;
  for (let i = 0; i < str.length; i++) {
    hash = ((hash << 5) + hash) + str.charCodeAt(i); // hash * 33 + c
  }
  return hash >>> 0; // Convert to unsigned 32-bit integer
}

/**
 * Serialize document state to a consistent JSON structure
 * Strips runtime-only fields and focuses on user-editable data
 */
export function serializeDocumentState(
  layers: Layer[],
  canvasSettings: CanvasSettings,
  effects?: EffectsConfig,
  activeLayerId?: string
): SerializableDocumentState {
  return {
    layers: layers.map(l => ({
      id: l.id,
      name: l.name,
      visible: l.visible,
      opacity: l.opacity,
      blendMode: l.blendMode,
      locked: l.locked,
      gradient: l.gradient,
      texture: l.texture,
      animation: l.animation,
      mask: l.mask,
    })),
    canvasSettings: {
      width: canvasSettings.width,
      height: canvasSettings.height,
      background: canvasSettings.backgroundColor,
    },
    effects,
    activeLayerId,
  };
}

/**
 * Hash document state for fast comparison
 * Returns a numeric hash that changes when any meaningful field changes
 */
export function hashDocumentState(
  layers: Layer[],
  canvasSettings: CanvasSettings,
  effects?: EffectsConfig,
  activeLayerId?: string
): number {
  const serialized = serializeDocumentState(layers, canvasSettings, effects, activeLayerId);
  const jsonString = JSON.stringify(serialized);
  return hashString(jsonString);
}

/**
 * Sanitize mask config before saving to autosave or history.
 *
 * BLOAT SOURCES stripped per field:
 *   previewImageUrl  — UI-only thumbnail, always regenerated at runtime (~2MB PNG data URL)
 *   imageUrl         — for SVG sources: regenerated by GradientCanvas from svgText (~2MB)
 *                      for bitmap uploads: KEPT (user's actual image, cannot be regenerated)
 *   svgText          — for preset library shapes (svgShapeId set): re-loaded from maskShapes (~96KB)
 *                      for user-uploaded SVGs (no svgShapeId): KEPT (only copy)
 *
 * Restoration path: GradientCanvas hydrates svgText from getShapeById(svgShapeId) in the
 * mask loading effect when svgText is absent but svgShapeId is present.
 */
function sanitizeMaskForStorage(mask: any): any {
  if (!mask) return mask;
  const result = { ...mask };

  // Always strip — pure UI thumbnail, regenerated at runtime
  delete result.previewImageUrl;

  if (result.sourceType === 'svg') {
    // imageUrl for SVG sources is either a stale leftover from a previous bitmap mask
    // or was generated by an earlier stroke-width rasterization. GradientCanvas
    // re-rasterizes from svgText, so imageUrl is never needed for SVG restore.
    delete result.imageUrl;

    // svgText for preset library shapes can be re-looked-up by svgShapeId at load time.
    // User-uploaded SVGs have no svgShapeId — their svgText is the only copy, keep it.
    if (result.svgShapeId && result.svgText) {
      delete result.svgText;
    }
  }
  // bitmap uploads: keep imageUrl (user's uploaded image, no other source)

  return result;
}

/**
 * Sanitize layer data by removing runtime-only and regeneratable fields.
 * Returns a clean layer object suitable for autosave and undo/redo history.
 */
export function sanitizeLayer(layer: Layer): Layer {
  return {
    id: layer.id,
    name: layer.name,
    visible: layer.visible,
    opacity: layer.opacity,
    blendMode: layer.blendMode,
    locked: layer.locked,
    gradient: layer.gradient,
    texture: layer.texture,
    animation: layer.animation,
    mask: sanitizeMaskForStorage(layer.mask),
    media: sanitizeMediaForStorage(layer.media),
  };
}

/**
 * Media Layer System (Stage 1): strip the runtime-only `src` before
 * persistence. Object URLs are invalid across sessions and poster-frame data
 * URLs would bloat autosave/history payloads (same rationale as stripping
 * mask imageUrl/svgText). Metadata survives so the panel can show a
 * "re-upload to restore" state after reload.
 */
export function sanitizeMediaForStorage(media: Layer['media']): Layer['media'] {
  if (!media) return undefined;
  const { src: _src, previewUrl: _previewUrl, blob: _blob, __rehydrated: _rehydrated, ...rest } = media as any;
  return rest;
}
